# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  displayName: 'Runtime Net Core 3.0.x'
  inputs:
    version: '3.0.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: 'Start Building Project $(BuildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project $(BuildConfiguration) to $(System.ArtifactsDirectory)'
  inputs:
    command: 'publish'
    projects: '**/$(NameProject).csproj'
    arguments: '--no-build --no-restore /p:Configuration=$(BuildConfiguration) /p:EnvironmentName=Production -o $(System.ArtifactsDirectory)'
    publishWebProjects: true

- task: PublishBuildArtifacts@1
  displayName: 'Artifacts $(System.ArtifactsDirectory)'
  inputs:
    pathtoPublish: '$(System.ArtifactsDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container'